# Generated by Django 3.2.9 on 2022-01-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TratamientoOdontologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamiento', models.CharField(max_length=40)),
                ('contenido', models.CharField(max_length=400)),
                ('autor', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pagina',
        ),
    ]
